version: '2'

services:
  client:
    build: "es_build"
    container_name: es_client
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - ./elasticsearch_client.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      esnet:
        ipv4_address: 172.28.1.1

  master:
    build: "es_build"
    container_name: es_master
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
     - ./elasticsearch_master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9300:9200
    networks:
      esnet:
        ipv4_address: 172.28.1.2

  data1:
    build: "es_build"
    container_name: es_data1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
     - ./elasticsearch_data1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9400:9200
    networks:
      esnet:
        ipv4_address: 172.28.1.3

  data2:
    build: "es_build"
    container_name: es_data2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
     - ./elasticsearch_data2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9500:9200
    networks:
      esnet:
        ipv4_address: 172.28.1.4

networks:
  esnet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
